name: Filebot CD

on:
  push:
    branches: [ prod_deploy ]
  pull_request:
    branches: [ prod_deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - name: Setup the SSH key
        env:
          WWW_SECRET_KEY: ${{ secrets.WWW_SECRET_KEY }}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

        run: |
          echo $HOME
          mkdir $HOME/.ssh
          echo "$WWW_SECRET_KEY" >> $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > $HOME/.ssh/known_hosts
          chmod 600 $HOME/.ssh/id_rsa

      - name: Deploy the app
        run: |
          scp -i $HOME/.ssh/id_rsa -r * www@jacobheric.com:/home/www/filebot
          ssh -i $HOME/.ssh/id www@jacobheric.com 'cd /home/www/filebot && pm2 restart filebot.config.js'
